services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    restart: always
    environment:
      BOT_NAME: "${BOT_NAME}"
      BOT_TOKEN: "${BOT_TOKEN}"
    ports:
      - "8081:8080"

  scrapper:
    build:
      context: ./scrapper
      dockerfile: Dockerfile
    container_name: scrapper
    restart: always
    ports:
      - "8082:8080"

