version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot
    restart: always
    environment:
      BOT_NAME: "${BOT_NAME}"
      BOT_TOKEN: "${BOT_TOKEN}"
    ports:
      - "8081:8080"
    depends_on:
      - scrapper

  scrapper:
    build:
      context: .
      dockerfile: scrapper/Dockerfile
    container_name: scrapper
    restart: always
    ports:
      - "8082:8080"
