name: Deploy to Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ closed ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /LinkTracker
            git pull origin master
            docker-compose build 
            docker-compose down
            docker-compose up -d

     
