name: Deploy to Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ closed ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
     - name: Debug SSH Key
       run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr ' ' '\n' | head -n 10

     
