name: CI/CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build and test project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Build Maven project
        run: mvn -B package --file pom.xml

  docker-build-and-push:
    name: Build Docker images and push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build bot Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/linktracker_bot:latest -f bot/Dockerfile .

      - name: Build scrapper Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/linktracker_scrapper:latest -f scrapper/Dockerfile .

      - name: Push bot Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/linktracker_bot:latest

      - name: Push scrapper Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/linktracker_scrapper:latest

  deploy:
    name: Deploy to remote server
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            cd app
            docker-compose down
            docker-compose pull
            docker-compose up -d
