name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-bot:
    name: Build Bot Module
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Test & build bot module
        run: mvn -B package --file pom.xml -pl bot -am

  build-scrapper:
    name: Build Scrapper Module
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Test & build scrapper module
        run: mvn -B package --file pom.xml -pl scrapper -am

  build-full:
    name: Build Full Project
    runs-on: ubuntu-latest
    needs: [build-bot, build-scrapper]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Test & build entire project
        run: mvn -B package --file pom.xml

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-full

    steps:
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd /LinkTracker
            git pull origin master
            mvn clean package -DskipTests
            docker-compose down
            docker-compose up -d
